from __future__ import annotations

import argparse
import bisect
import csv
import resource
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from agpt_ultra.data import CharVocab, make_circular_samples, make_samples, read_text
from agpt_ultra.flat_ops import samples_to_flat_trie
from agpt_ultra.run_ids import prefixed_path, resolve_run_id


@dataclass(frozen=True)
class SubtrieProfileRow:
    token_id: int
    token_repr: str
    sample_count: int
    node_count: int
    predictive_node_count: int
    max_depth: int
    transition_mass: int
    build_sec: float
    tensor_bytes: int
    peak_rss_kb: int


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Profile one-prefix-at-a-time unigram trie construction.")
    parser.add_argument("--input", type=Path, default=Path("data/input.txt"))
    parser.add_argument("--output", type=Path, default=Path("runs/unigram_subtries.csv"))
    parser.add_argument("--run-id", type=str, default=None, help="Prefix output artifacts for a new run. Generated by default.")
    parser.add_argument("--block-size", type=int, default=16)
    parser.add_argument("--stride", type=int, default=1)
    parser.add_argument("--train-fraction", type=float, default=1.0)
    parser.add_argument("--no-circular", action="store_true", help="Use ordinary non-wrapped samples instead of circular samples.")
    parser.add_argument("--limit-tokens", type=str, default=None, help="Optional literal string of first tokens to profile.")
    return parser.parse_args()


def token_label(token: str) -> str:
    return repr(token)


def trie_tensor_bytes(trie) -> int:
    return sum(
        tensor.numel() * tensor.element_size()
        for tensor in (trie.parents, trie.tokens, trie.depths, trie.counts, trie.transition_counts)
    )


def prefix_range(sorted_windows: list[str], vocab_chars: tuple[str, ...], token_index: int) -> tuple[int, int]:
    token = vocab_chars[token_index]
    lo = bisect.bisect_left(sorted_windows, token)
    if token_index + 1 < len(vocab_chars):
        hi = bisect.bisect_left(sorted_windows, vocab_chars[token_index + 1])
    else:
        hi = len(sorted_windows)
    return lo, hi


def write_rows(path: Path, rows: list[SubtrieProfileRow]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(asdict(rows[0]).keys()) if rows else list(SubtrieProfileRow.__dataclass_fields__))
        writer.writeheader()
        for row in rows:
            writer.writerow(asdict(row))


def main() -> None:
    args = parse_args()
    args.run_id = resolve_run_id(args.run_id)
    args.output = prefixed_path(args.output, args.run_id)
    text = read_text(args.input)
    if not 0.0 < args.train_fraction <= 1.0:
        raise ValueError("train_fraction must be in (0, 1]")
    if args.train_fraction < 1.0:
        text = text[: int(len(text) * args.train_fraction)]

    vocab = CharVocab.from_text(text)
    make = make_samples if args.no_circular else make_circular_samples

    started = time.perf_counter()
    samples = make(text, block_size=args.block_size, stride=args.stride)
    sample_sec = time.perf_counter() - started
    started = time.perf_counter()
    samples.sort()
    sort_sec = time.perf_counter() - started

    token_filter = set(args.limit_tokens) if args.limit_tokens is not None else None
    rows: list[SubtrieProfileRow] = []
    total_nodes = 0
    total_predictive_nodes = 0
    total_mass = 0
    total_tensor_bytes = 0
    total_build_sec = 0.0

    print(
        f"chars={len(text)} samples={len(samples)} block_size={args.block_size} "
        f"stride={args.stride} circular={not args.no_circular} "
        f"run_id={args.run_id} output={args.output} sample_sec={sample_sec:.4f} sort_sec={sort_sec:.4f}",
        flush=True,
    )

    for token_index, token in enumerate(vocab.chars):
        if token_filter is not None and token not in token_filter:
            continue
        lo, hi = prefix_range(samples, vocab.chars, token_index)
        token_samples = samples[lo:hi]
        if not token_samples:
            continue

        started = time.perf_counter()
        trie = samples_to_flat_trie(token_samples, vocab)
        build_sec = time.perf_counter() - started

        node_count = trie.node_count
        predictive_node_count = int(trie.predictive_node_mask.sum().item())
        max_depth = int(trie.depths.max().item())
        transition_mass = int(trie.transition_counts.sum().item())
        tensor_bytes = trie_tensor_bytes(trie)
        peak_rss_kb = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss

        row = SubtrieProfileRow(
            token_id=token_index,
            token_repr=token_label(token),
            sample_count=len(token_samples),
            node_count=node_count,
            predictive_node_count=predictive_node_count,
            max_depth=max_depth,
            transition_mass=transition_mass,
            build_sec=build_sec,
            tensor_bytes=tensor_bytes,
            peak_rss_kb=peak_rss_kb,
        )
        rows.append(row)
        total_nodes += node_count
        total_predictive_nodes += predictive_node_count
        total_mass += transition_mass
        total_tensor_bytes += tensor_bytes
        total_build_sec += build_sec
        print(
            f"token={row.token_repr} samples={row.sample_count} nodes={row.node_count} "
            f"predictive={row.predictive_node_count} mass={row.transition_mass} "
            f"build_sec={row.build_sec:.4f} tensor_mb={row.tensor_bytes / 1024 / 1024:.2f} "
            f"peak_rss_mb={row.peak_rss_kb / 1024:.1f}",
            flush=True,
        )

    write_rows(args.output, rows)
    print(
        f"total_profiled_tokens={len(rows)} total_nodes={total_nodes} "
        f"total_predictive_nodes={total_predictive_nodes} total_mass={total_mass} "
        f"total_build_sec={total_build_sec:.4f} total_tensor_mb={total_tensor_bytes / 1024 / 1024:.2f} "
        f"wrote={args.output}",
        flush=True,
    )


if __name__ == "__main__":
    main()
