from __future__ import annotations

import argparse
import csv
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Literal

import torch
import torch.nn.functional as F

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from agpt_ultra.data import CharVocab, read_text
from agpt_ultra.eval import evaluate_sequential_text_loss, split_text
from agpt_ultra.head_only import (
    BatchedHeadEvidence,
    batched_head_fisher_matvec,
    head_shape,
    load_head_theta,
    model_head_theta,
    natural_head_step_matrix_free,
    quadratic_predicted_improvement,
    suggested_quadratic_step_scale,
    trust_radius_step_scale,
)
from agpt_ultra.model import TinyCharRNN
from agpt_ultra.run_ids import prefixed_path, resolve_run_id


@dataclass(frozen=True)
class SequenceTrainRow:
    step: int
    train_loss: float
    seq_val_nll: float | None
    seq_val_ppl: float | None
    seq_val_bpc: float | None
    runtime_sec: float
    eval_sec: float | None
    body_lr: float
    mode: str
    head_cg_iters: int | None = None
    head_step_scale: float | None = None
    head_predicted_improvement: float | None = None
    head_linear_term: float | None = None
    head_fisher_quadratic: float | None = None
    head_eta_quad: float | None = None
    head_eta_trust: float | None = None


def parse_step_scale(value: str) -> float | Literal["auto"]:
    if value == "auto":
        return value
    return float(value)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train TinyCharRNN as a conventional sequence language model.")
    parser.add_argument("--input", type=Path, default=Path("data/input.txt"))
    parser.add_argument("--output", type=Path, default=Path("runs/sequence_trainer.csv"))
    parser.add_argument("--run-id", type=str, default=None, help="Prefix output artifacts for a new run. Generated by default.")
    parser.add_argument("--seed", type=int, default=1337)
    parser.add_argument("--mode", choices=["adam", "body-adam-head-fisher"], default="adam")
    parser.add_argument("--train-fraction", type=float, default=0.9)
    parser.add_argument("--max-train-chars", type=int, default=None)
    parser.add_argument("--eval-max-chars", type=int, default=None)
    parser.add_argument("--steps", type=int, default=1000)
    parser.add_argument("--batch-size", type=int, default=64)
    parser.add_argument("--block-size", type=int, default=128)
    parser.add_argument("--hidden-size", type=int, default=64)
    parser.add_argument("--embedding-size", type=int, default=64)
    parser.add_argument("--lr", type=float, default=3e-3)
    parser.add_argument("--max-grad-norm", type=float, default=1.0)
    parser.add_argument("--eval-every", type=int, default=100)
    parser.add_argument("--eval-chunk-size", type=int, default=2048)
    parser.add_argument("--head-damping", type=float, default=50.0)
    parser.add_argument("--head-step-scale", default="auto")
    parser.add_argument("--max-head-step-scale", type=float, default=1.0)
    parser.add_argument("--head-trust-radius", type=float, default=200.0)
    parser.add_argument("--max-cg-iter", type=int, default=8)
    parser.add_argument("--cg-tolerance", type=float, default=1e-6)
    return parser.parse_args()


def encode_text(vocab: CharVocab, text: str) -> torch.Tensor:
    return torch.tensor(vocab.encode(text), dtype=torch.long)


def sample_batch(encoded: torch.Tensor, batch_size: int, block_size: int, generator: torch.Generator) -> tuple[torch.Tensor, torch.Tensor]:
    if encoded.numel() <= block_size:
        raise ValueError("encoded text must be longer than block_size")
    starts = torch.randint(0, encoded.numel() - block_size, (batch_size,), generator=generator)
    x = torch.stack([encoded[start : start + block_size] for start in starts])
    y = torch.stack([encoded[start + 1 : start + block_size + 1] for start in starts])
    return x, y


def sequence_hidden_states(model: TinyCharRNN, input_ids: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
    batch, length = input_ids.shape
    state = model.initial_state(batch, input_ids.device)
    hidden = []
    logits = []
    for position in range(length):
        step_logits, state = model.step(input_ids[:, position], state)
        logits.append(step_logits)
        hidden.append(state)
    return torch.stack(hidden, dim=1), torch.stack(logits, dim=1)


@torch.no_grad()
def collect_sequence_head_evidence(model: TinyCharRNN, hidden: torch.Tensor, targets: torch.Tensor, theta: torch.Tensor | None = None) -> BatchedHeadEvidence:
    if theta is None:
        theta = model_head_theta(model)
    theta = theta.detach().clone()
    shape = head_shape(model)
    flat_hidden = hidden.reshape(-1, hidden.shape[-1]).to(dtype=theta.dtype)
    flat_targets = targets.reshape(-1)
    weight = theta[: shape.vocab_size * shape.hidden_size].reshape(shape.vocab_size, shape.hidden_size)
    bias = theta[shape.vocab_size * shape.hidden_size :]
    logits = flat_hidden @ weight.T + bias
    predicted = torch.softmax(logits, dim=1)
    target = torch.zeros_like(predicted)
    target.scatter_(1, flat_targets[:, None], 1.0)
    residual = predicted - target
    weight_gradient = residual.T @ flat_hidden
    bias_gradient = residual.sum(dim=0)
    features = torch.cat([flat_hidden, flat_hidden.new_ones((flat_hidden.shape[0], 1))], dim=1)
    return BatchedHeadEvidence(
        gradient=torch.cat([weight_gradient.reshape(-1), bias_gradient]),
        features=features.detach().clone(),
        predicted=predicted.detach().clone(),
        counts=flat_hidden.new_ones(flat_hidden.shape[0]),
        shape=shape,
    )


def set_head_requires_grad(model: TinyCharRNN, requires_grad: bool) -> list[bool]:
    previous = [param.requires_grad for param in model.head.parameters()]
    for param in model.head.parameters():
        param.requires_grad_(requires_grad)
    return previous


def restore_head_requires_grad(model: TinyCharRNN, previous: list[bool]) -> None:
    for param, requires_grad in zip(model.head.parameters(), previous, strict=True):
        param.requires_grad_(requires_grad)


def evaluate(model: TinyCharRNN, vocab: CharVocab, val_text: str, chunk_size: int) -> tuple[float, float, float, float]:
    started = time.perf_counter()
    metrics = evaluate_sequential_text_loss(model, vocab, val_text, chunk_size=chunk_size)
    return metrics.nll_per_token, metrics.perplexity, metrics.bits_per_char, time.perf_counter() - started


def write_header(path: Path) -> tuple[csv.DictWriter, object]:
    path.parent.mkdir(parents=True, exist_ok=True)
    handle = path.open("w", newline="", encoding="utf-8")
    writer = csv.DictWriter(
        handle,
        fieldnames=list(asdict(SequenceTrainRow(0, 0.0, None, None, None, 0.0, None, 0.0, "adam")).keys()),
    )
    writer.writeheader()
    handle.flush()
    return writer, handle


def main() -> None:
    args = parse_args()
    args.run_id = resolve_run_id(args.run_id)
    args.output = prefixed_path(args.output, args.run_id)
    args.head_step_scale = parse_step_scale(args.head_step_scale)
    torch.manual_seed(args.seed)
    generator = torch.Generator().manual_seed(args.seed)

    text = read_text(args.input)
    split = split_text(text, train_fraction=args.train_fraction)
    vocab = CharVocab.from_text(text)
    train_text = split.train_text[: args.max_train_chars] if args.max_train_chars is not None else split.train_text
    eval_text = split.val_text[: args.eval_max_chars] if args.eval_max_chars is not None else split.val_text
    train_ids = encode_text(vocab, train_text)
    model = TinyCharRNN(vocab.size, n_embd=args.embedding_size, n_hidden=args.hidden_size)
    if args.mode == "adam":
        optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr)
    else:
        optimizer = torch.optim.AdamW([*model.embed.parameters(), *model.cell.parameters()], lr=args.lr)

    writer, handle = write_header(args.output)
    print(
        f"mode={args.mode} train_chars={len(train_text)} val_chars={len(eval_text)} "
        f"steps={args.steps} batch_size={args.batch_size} block_size={args.block_size} "
        f"hidden_size={args.hidden_size} embedding_size={args.embedding_size} "
        f"run_id={args.run_id} output={args.output}",
        flush=True,
    )
    try:
        for step in range(1, args.steps + 1):
            started = time.perf_counter()
            x, y = sample_batch(train_ids, args.batch_size, args.block_size, generator)
            if args.mode == "adam":
                logits = model(x)
                loss = F.cross_entropy(logits.reshape(-1, vocab.size), y.reshape(-1))
                optimizer.zero_grad(set_to_none=True)
                loss.backward()
                if args.max_grad_norm is not None:
                    torch.nn.utils.clip_grad_norm_(model.parameters(), args.max_grad_norm)
                optimizer.step()
                head_cg_iters = None
                head_step_scale = None
                head_predicted_improvement = None
                head_linear_term = None
                head_fisher_quadratic = None
                head_eta_quad = None
                head_eta_trust = None
            else:
                head_requires_grad = set_head_requires_grad(model, False)
                try:
                    _, logits = sequence_hidden_states(model, x)
                    loss = F.cross_entropy(logits.reshape(-1, vocab.size), y.reshape(-1))
                    optimizer.zero_grad(set_to_none=True)
                    loss.backward()
                    if args.max_grad_norm is not None:
                        torch.nn.utils.clip_grad_norm_([*model.embed.parameters(), *model.cell.parameters()], args.max_grad_norm)
                    optimizer.step()
                finally:
                    restore_head_requires_grad(model, head_requires_grad)

                with torch.no_grad():
                    hidden, logits = sequence_hidden_states(model, x)
                    loss = F.cross_entropy(logits.reshape(-1, vocab.size), y.reshape(-1))
                    theta = model_head_theta(model)
                    evidence = collect_sequence_head_evidence(model, hidden, y, theta)
                    cg = natural_head_step_matrix_free(
                        evidence,
                        damping=args.head_damping,
                        max_cg_iter=args.max_cg_iter,
                        cg_tolerance=args.cg_tolerance,
                    )
                    fisher_delta = batched_head_fisher_matvec(cg.solution, evidence)
                    head_linear_term = evidence.gradient.dot(cg.solution).item()
                    head_fisher_quadratic = cg.solution.dot(fisher_delta).item()
                    head_eta_quad = suggested_quadratic_step_scale(
                        evidence.gradient,
                        cg.solution,
                        fisher_delta,
                        max_step_scale=args.max_head_step_scale,
                    )
                    head_eta_trust = trust_radius_step_scale(head_fisher_quadratic, args.head_trust_radius)
                    if args.head_step_scale == "auto":
                        head_step_scale = head_eta_quad
                        if head_eta_trust is not None:
                            head_step_scale = min(head_step_scale, head_eta_trust)
                    else:
                        head_step_scale = float(args.head_step_scale)
                    head_predicted_improvement = quadratic_predicted_improvement(
                        evidence.gradient,
                        cg.solution,
                        fisher_delta,
                        head_step_scale,
                    )
                    load_head_theta(model, theta + head_step_scale * cg.solution)
                    head_cg_iters = cg.iterations

            runtime = time.perf_counter() - started
            should_eval = step == 1 or step == args.steps or (args.eval_every > 0 and step % args.eval_every == 0)
            if should_eval:
                nll, ppl, bpc, eval_sec = evaluate(model, vocab, eval_text, args.eval_chunk_size)
            else:
                nll = ppl = bpc = eval_sec = None
            row = SequenceTrainRow(
                step=step,
                train_loss=loss.item(),
                seq_val_nll=nll,
                seq_val_ppl=ppl,
                seq_val_bpc=bpc,
                runtime_sec=runtime,
                eval_sec=eval_sec,
                body_lr=args.lr,
                mode=args.mode,
                head_cg_iters=head_cg_iters,
                head_step_scale=head_step_scale,
                head_predicted_improvement=head_predicted_improvement,
                head_linear_term=head_linear_term,
                head_fisher_quadratic=head_fisher_quadratic,
                head_eta_quad=head_eta_quad,
                head_eta_trust=head_eta_trust,
            )
            writer.writerow(asdict(row))
            handle.flush()
            if should_eval:
                print(
                    f"step={step:05d} train_loss={loss.item():.4f} seq_val_ppl={ppl:.2f} "
                    f"runtime_sec={runtime:.3f} head_step_scale={head_step_scale}",
                    flush=True,
                )
    finally:
        handle.close()
    print(f"wrote={args.output}", flush=True)


if __name__ == "__main__":
    main()
