from __future__ import annotations

import argparse
import csv
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path

import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from agpt_ultra.data import CharVocab, read_text
from agpt_ultra.eval import evaluate_sequential_text_loss, evaluate_trie_loss, make_sample_split, split_text
from agpt_ultra.flat_ops import samples_to_flat_trie
from agpt_ultra.hybrid import freeze_embeddings, hybrid_epoch
from agpt_ultra.model import TinyCharRNN
from agpt_ultra.run_ids import prefixed_path, resolve_run_id


@dataclass(frozen=True)
class HybridStressRow:
    seed: int
    epoch: int
    train_loss: float
    before_loss: float | None
    after_body_loss: float | None
    val_nll: float
    val_ppl: float
    seq_val_nll: float | None
    seq_val_ppl: float | None
    seq_val_bpc: float | None
    runtime_sec: float
    body_lr: float | None = None
    before_loss_runtime_sec: float | None = None
    body_runtime_sec: float | None = None
    hidden_cache_runtime_sec: float | None = None
    head_runtime_sec: float | None = None
    val_runtime_sec: float | None = None
    seq_val_runtime_sec: float | None = None
    cg_iters: int | None = None
    step_scale: float | None = None
    suggested_step_scale: float | None = None
    predicted_improvement: float | None = None
    train_actual_improvement: float | None = None
    train_improvement_ratio: float | None = None
    val_actual_improvement: float | None = None
    val_improvement_ratio: float | None = None
    linear_term: float | None = None
    fisher_quadratic: float | None = None
    eta_quad: float | None = None
    eta_trust: float | None = None
    trust_radius: float | None = None


class RowWriter:
    def __init__(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        self.handle = path.open("w", newline="", encoding="utf-8")
        self.writer = csv.DictWriter(self.handle, fieldnames=list(asdict(HybridStressRow(0, 0, 0.0, None, None, 0.0, 0.0, None, None, None, 0.0)).keys()))
        self.writer.writeheader()
        self.handle.flush()
        self.count = 0

    def write(self, row: HybridStressRow) -> None:
        self.writer.writerow(asdict(row))
        self.handle.flush()
        self.count += 1

    def close(self) -> None:
        self.handle.close()


def parse_step_scale(value: str) -> float | str:
    if value == "auto":
        return value
    return float(value)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run flushed hybrid-only trie Fisher stress tests.")
    parser.add_argument("--input", type=Path, default=Path("data/input.txt"))
    parser.add_argument("--output", type=Path, default=Path("runs/hybrid_stress.csv"))
    parser.add_argument("--run-id", type=str, default=None, help="Prefix output artifacts for a new run. Generated by default.")
    parser.add_argument("--seeds", type=int, nargs="+", default=[1337])
    parser.add_argument("--block-size", type=int, default=16)
    parser.add_argument("--stride", type=int, default=16)
    parser.add_argument("--train-fraction", type=float, default=0.9)
    parser.add_argument("--max-train-samples", type=int, default=8192)
    parser.add_argument("--max-val-samples", type=int, default=2048)
    parser.add_argument("--epochs", type=int, default=20)
    parser.add_argument("--hidden-size", type=int, default=16)
    parser.add_argument("--embedding-size", type=int, default=16)
    parser.add_argument("--update-embeddings", action="store_true")
    parser.add_argument("--body-lr", type=float, default=3e-3)
    parser.add_argument("--body-lr-schedule", nargs="*", default=None, help="Optional epoch:lr milestones, e.g. 1:0.003 51:0.001.")
    parser.add_argument("--head-damping", type=float, default=50.0)
    parser.add_argument("--head-step-scale", default="auto")
    parser.add_argument("--max-head-step-scale", type=float, default=1.0)
    parser.add_argument("--head-trust-radius", type=float, default=200.0)
    parser.add_argument("--line-search-steps", type=int, default=4)
    parser.add_argument("--line-search-target", choices=["train", "val"], default="train")
    parser.add_argument("--compute-before-loss", action="store_true", help="Compute diagnostic train loss before the body update.")
    parser.add_argument("--sequential-val", action="store_true", help="Also evaluate raw validation text with continuous recurrent state.")
    parser.add_argument("--sequential-val-chunk-size", type=int, default=1024)
    parser.add_argument("--max-cg-iter", type=int, default=8)
    parser.add_argument("--cg-tolerance", type=float, default=1e-6)
    parser.add_argument("--max-grad-norm", type=float, default=1.0)
    return parser.parse_args()


def make_model(seed: int, vocab_size: int, embedding_size: int, hidden_size: int, update_embeddings: bool = False) -> TinyCharRNN:
    torch.manual_seed(seed)
    model = TinyCharRNN(vocab_size, n_embd=embedding_size, n_hidden=hidden_size)
    if not update_embeddings:
        freeze_embeddings(model)
    return model


def parse_lr_schedule(values: list[str] | None, default_lr: float) -> list[tuple[int, float]]:
    if not values:
        return [(1, default_lr)]
    schedule: list[tuple[int, float]] = []
    for value in values:
        epoch_text, lr_text = value.split(":", maxsplit=1)
        epoch = int(epoch_text)
        lr = float(lr_text)
        if epoch < 1:
            raise ValueError("body LR schedule epochs must be >= 1")
        schedule.append((epoch, lr))
    schedule.sort()
    if schedule[0][0] != 1:
        schedule.insert(0, (1, default_lr))
    return schedule


def scheduled_lr(schedule: list[tuple[int, float]], epoch: int) -> float:
    lr = schedule[0][1]
    for start_epoch, candidate_lr in schedule:
        if epoch < start_epoch:
            break
        lr = candidate_lr
    return lr


def set_optimizer_lr(optimizer: torch.optim.Optimizer, lr: float) -> None:
    for group in optimizer.param_groups:
        group["lr"] = lr


def print_row(row: HybridStressRow) -> None:
    seq_text = ""
    if row.seq_val_ppl is not None and row.seq_val_bpc is not None:
        seq_text = f"seq_val_ppl={row.seq_val_ppl:.2f} seq_val_bpc={row.seq_val_bpc:.3f} "
    print(
        f"seed={row.seed} "
        f"epoch={row.epoch:03d} "
        f"train_loss={row.train_loss:.4f} "
        f"val_ppl={row.val_ppl:.2f} "
        f"{seq_text}"
        f"runtime_sec={row.runtime_sec:.2f} "
        f"body_lr={row.body_lr} "
        f"body_sec={row.body_runtime_sec} "
        f"cache_sec={row.hidden_cache_runtime_sec} "
        f"head_sec={row.head_runtime_sec} "
        f"val_sec={row.val_runtime_sec} "
        f"seq_val_sec={row.seq_val_runtime_sec} "
        f"step_scale={row.step_scale} "
        f"eta_quad={row.eta_quad} "
        f"eta_trust={row.eta_trust} "
        f"rho_train={row.train_improvement_ratio} "
        f"rho_val={row.val_improvement_ratio}",
        flush=True,
    )


def main() -> None:
    args = parse_args()
    args.run_id = resolve_run_id(args.run_id)
    args.output = prefixed_path(args.output, args.run_id)
    args.head_step_scale = parse_step_scale(args.head_step_scale)
    lr_schedule = parse_lr_schedule(args.body_lr_schedule, args.body_lr)

    text = read_text(args.input)
    vocab = CharVocab.from_text(text)
    text_split = split_text(text, train_fraction=args.train_fraction)
    split = make_sample_split(
        text,
        block_size=args.block_size,
        stride=args.stride,
        train_fraction=args.train_fraction,
        max_train_samples=args.max_train_samples,
        max_val_samples=args.max_val_samples,
    )
    train_trie = samples_to_flat_trie(split.train_samples, vocab)
    val_trie = samples_to_flat_trie(split.val_samples, vocab)

    writer = RowWriter(args.output)
    try:
        for seed in args.seeds:
            model = make_model(seed, vocab.size, args.embedding_size, args.hidden_size, update_embeddings=args.update_embeddings)
            body_params = [*model.cell.parameters()]
            if args.update_embeddings:
                body_params.extend(model.embed.parameters())
            optimizer = torch.optim.AdamW(body_params, lr=args.body_lr)
            seq_val_runtime = None
            val = evaluate_trie_loss(model, vocab, val_trie)
            seq_val = None
            if args.sequential_val:
                seq_val_started = time.perf_counter()
                seq_val = evaluate_sequential_text_loss(model, vocab, text_split.val_text, chunk_size=args.sequential_val_chunk_size)
                seq_val_runtime = time.perf_counter() - seq_val_started
            row = HybridStressRow(
                seed,
                0,
                float("nan"),
                None,
                None,
                val.nll_per_token,
                val.perplexity,
                seq_val.nll_per_token if seq_val is not None else None,
                seq_val.perplexity if seq_val is not None else None,
                seq_val.bits_per_char if seq_val is not None else None,
                0.0,
                None,
                None,
                None,
                None,
                None,
                None,
                seq_val_runtime,
            )
            writer.write(row)
            print_row(row)

            for epoch in range(1, args.epochs + 1):
                body_lr = scheduled_lr(lr_schedule, epoch)
                set_optimizer_lr(optimizer, body_lr)
                started = time.perf_counter()
                result = hybrid_epoch(
                    model,
                    vocab,
                    split.train_samples,
                    body_optimizer=optimizer,
                    head_damping=args.head_damping,
                    head_step_scale=args.head_step_scale,
                    max_grad_norm=args.max_grad_norm,
                    max_cg_iter=args.max_cg_iter,
                    cg_tolerance=args.cg_tolerance,
                    flat_trie=train_trie,
                    max_head_step_scale=args.max_head_step_scale,
                    line_search_steps=args.line_search_steps,
                    line_search_flat_trie=val_trie if args.line_search_target == "val" else None,
                    calibration_flat_trie=val_trie,
                    trust_radius=args.head_trust_radius,
                    compute_before_loss=args.compute_before_loss,
                    update_embeddings=args.update_embeddings,
                )
                runtime = time.perf_counter() - started
                val_started = time.perf_counter()
                val = evaluate_trie_loss(model, vocab, val_trie)
                val_runtime = time.perf_counter() - val_started
                seq_val = None
                seq_val_runtime = None
                if args.sequential_val:
                    seq_val_started = time.perf_counter()
                    seq_val = evaluate_sequential_text_loss(model, vocab, text_split.val_text, chunk_size=args.sequential_val_chunk_size)
                    seq_val_runtime = time.perf_counter() - seq_val_started
                head = result.head_result
                row = HybridStressRow(
                    seed,
                    epoch,
                    result.after_loss,
                    result.before_loss,
                    result.after_body_loss,
                    val.nll_per_token,
                    val.perplexity,
                    seq_val.nll_per_token if seq_val is not None else None,
                    seq_val.perplexity if seq_val is not None else None,
                    seq_val.bits_per_char if seq_val is not None else None,
                    runtime,
                    body_lr,
                    result.before_loss_runtime_sec,
                    result.body_runtime_sec,
                    result.hidden_cache_runtime_sec,
                    result.head_runtime_sec,
                    val_runtime,
                    seq_val_runtime,
                    head.cg_iterations,
                    head.step_scale,
                    head.suggested_step_scale,
                    head.predicted_improvement,
                    head.train_actual_improvement,
                    head.train_improvement_ratio,
                    head.val_actual_improvement,
                    head.val_improvement_ratio,
                    head.linear_term,
                    head.fisher_quadratic,
                    head.eta_quad,
                    head.eta_trust,
                    head.trust_radius,
                )
                writer.write(row)
                print_row(row)
            print(f"finished seed={seed}", flush=True)
    finally:
        writer.close()
    print(f"wrote {writer.count} rows to {args.output}", flush=True)


if __name__ == "__main__":
    main()
