from __future__ import annotations

import argparse
import csv
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path

import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from agpt_ultra.baseline import baseline_epoch, baseline_parameters
from agpt_ultra.data import CharVocab, read_text
from agpt_ultra.eval import evaluate_trie_loss, make_sample_split
from agpt_ultra.flat_ops import samples_to_flat_trie
from agpt_ultra.hybrid import freeze_embeddings, hybrid_epoch
from agpt_ultra.model import TinyCharRNN
from agpt_ultra.run_ids import prefixed_path, resolve_run_id


@dataclass(frozen=True)
class ComparisonRow:
    seed: int
    method: str
    epoch: int
    train_loss: float
    val_nll: float
    val_ppl: float
    runtime_sec: float
    cg_iters: int | None = None
    step_scale: float | None = None
    suggested_step_scale: float | None = None
    predicted_improvement: float | None = None
    actual_improvement: float | None = None
    improvement_ratio: float | None = None
    train_actual_improvement: float | None = None
    train_improvement_ratio: float | None = None
    val_actual_improvement: float | None = None
    val_improvement_ratio: float | None = None
    linear_term: float | None = None
    fisher_quadratic: float | None = None
    eta_quad: float | None = None
    eta_trust: float | None = None
    trust_radius: float | None = None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Compare AdamW baseline and trie Fisher hybrid.")
    parser.add_argument("--input", type=Path, default=Path("data/input.txt"))
    parser.add_argument("--output", type=Path, default=Path("runs/comparison.csv"))
    parser.add_argument("--run-id", type=str, default=None, help="Prefix output artifacts for a new run. Generated by default.")
    parser.add_argument("--seeds", type=int, nargs="+", default=[1337, 1338, 1339])
    parser.add_argument("--block-size", type=int, default=32)
    parser.add_argument("--stride", type=int, default=32)
    parser.add_argument("--train-fraction", type=float, default=0.9)
    parser.add_argument("--max-train-samples", type=int, default=512)
    parser.add_argument("--max-val-samples", type=int, default=128)
    parser.add_argument("--epochs", type=int, default=5)
    parser.add_argument("--hidden-size", type=int, default=8)
    parser.add_argument("--embedding-size", type=int, default=8)
    parser.add_argument("--baseline-lr", type=float, default=3e-3)
    parser.add_argument("--hybrid-body-lr", type=float, default=3e-3)
    parser.add_argument("--head-damping", type=float, default=50.0)
    parser.add_argument("--head-step-scale", default="0.5")
    parser.add_argument("--max-head-step-scale", type=float, default=1.0)
    parser.add_argument("--head-trust-radius", type=float, default=None)
    parser.add_argument("--line-search-steps", type=int, default=0)
    parser.add_argument("--line-search-target", choices=["train", "val"], default="train")
    parser.add_argument("--max-cg-iter", type=int, default=32)
    parser.add_argument("--cg-tolerance", type=float, default=1e-6)
    parser.add_argument("--max-grad-norm", type=float, default=1.0)
    return parser.parse_args()


def make_model(seed: int, vocab_size: int, embedding_size: int, hidden_size: int) -> TinyCharRNN:
    torch.manual_seed(seed)
    model = TinyCharRNN(vocab_size, n_embd=embedding_size, n_hidden=hidden_size)
    freeze_embeddings(model)
    return model


def run_baseline(args: argparse.Namespace, vocab: CharVocab, samples, train_trie, val_trie, seed: int) -> list[ComparisonRow]:
    model = make_model(seed, vocab.size, args.embedding_size, args.hidden_size)
    optimizer = torch.optim.AdamW(baseline_parameters(model), lr=args.baseline_lr)
    rows: list[ComparisonRow] = []

    val = evaluate_trie_loss(model, vocab, val_trie)
    rows.append(ComparisonRow(seed, "baseline", 0, float("nan"), val.nll_per_token, val.perplexity, 0.0))
    for epoch in range(1, args.epochs + 1):
        started = time.perf_counter()
        result = baseline_epoch(
            model,
            vocab,
            samples.train_samples,
            optimizer=optimizer,
            max_grad_norm=args.max_grad_norm,
            flat_trie=train_trie,
        )
        runtime = time.perf_counter() - started
        val = evaluate_trie_loss(model, vocab, val_trie)
        rows.append(
            ComparisonRow(seed, "baseline", epoch, result.after_loss, val.nll_per_token, val.perplexity, runtime)
        )
    return rows


def run_hybrid(args: argparse.Namespace, vocab: CharVocab, samples, train_trie, val_trie, seed: int) -> list[ComparisonRow]:
    model = make_model(seed, vocab.size, args.embedding_size, args.hidden_size)
    optimizer = torch.optim.AdamW(model.cell.parameters(), lr=args.hybrid_body_lr)
    rows: list[ComparisonRow] = []

    val = evaluate_trie_loss(model, vocab, val_trie)
    rows.append(ComparisonRow(seed, "hybrid", 0, float("nan"), val.nll_per_token, val.perplexity, 0.0))
    for epoch in range(1, args.epochs + 1):
        started = time.perf_counter()
        result = hybrid_epoch(
            model,
            vocab,
            samples.train_samples,
            body_optimizer=optimizer,
            head_damping=args.head_damping,
            head_step_scale=args.head_step_scale,
            max_grad_norm=args.max_grad_norm,
            max_cg_iter=args.max_cg_iter,
            cg_tolerance=args.cg_tolerance,
            flat_trie=train_trie,
            max_head_step_scale=args.max_head_step_scale,
            line_search_steps=args.line_search_steps,
            line_search_flat_trie=val_trie if args.line_search_target == "val" else None,
            calibration_flat_trie=val_trie,
            trust_radius=args.head_trust_radius,
        )
        runtime = time.perf_counter() - started
        val = evaluate_trie_loss(model, vocab, val_trie)
        rows.append(
            ComparisonRow(
                seed,
                "hybrid",
                epoch,
                result.after_loss,
                val.nll_per_token,
                val.perplexity,
                runtime,
                result.head_result.cg_iterations,
                result.head_result.step_scale,
                result.head_result.suggested_step_scale,
                result.head_result.predicted_improvement,
                result.head_result.actual_improvement,
                result.head_result.improvement_ratio,
                result.head_result.train_actual_improvement,
                result.head_result.train_improvement_ratio,
                result.head_result.val_actual_improvement,
                result.head_result.val_improvement_ratio,
                result.head_result.linear_term,
                result.head_result.fisher_quadratic,
                result.head_result.eta_quad,
                result.head_result.eta_trust,
                result.head_result.trust_radius,
            )
        )
    return rows


def write_rows(path: Path, rows: list[ComparisonRow]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(asdict(rows[0]).keys()))
        writer.writeheader()
        for row in rows:
            writer.writerow(asdict(row))


class RowWriter:
    def __init__(self, path: Path) -> None:
        self.path = path
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.handle = self.path.open("w", newline="", encoding="utf-8")
        fieldnames = list(asdict(ComparisonRow(0, "", 0, 0.0, 0.0, 0.0, 0.0)).keys())
        self.writer = csv.DictWriter(self.handle, fieldnames=fieldnames)
        self.writer.writeheader()
        self.handle.flush()
        self.count = 0

    def write(self, row: ComparisonRow) -> None:
        self.writer.writerow(asdict(row))
        self.handle.flush()
        self.count += 1

    def close(self) -> None:
        self.handle.close()


def print_row(row: ComparisonRow) -> None:
    print(
        f"seed={row.seed} "
        f"method={row.method} "
        f"epoch={row.epoch:03d} "
        f"train_loss={row.train_loss:.4f} "
        f"val_nll={row.val_nll:.4f} "
        f"val_ppl={row.val_ppl:.2f} "
        f"runtime_sec={row.runtime_sec:.2f} "
        f"cg_iters={row.cg_iters} "
        f"step_scale={row.step_scale} "
        f"suggested_step_scale={row.suggested_step_scale} "
        f"predicted_improvement={row.predicted_improvement} "
        f"actual_improvement={row.actual_improvement} "
        f"improvement_ratio={row.improvement_ratio} "
        f"rho_train={row.train_improvement_ratio} "
        f"rho_val={row.val_improvement_ratio} "
        f"eta_quad={row.eta_quad} "
        f"eta_trust={row.eta_trust}",
        flush=True,
    )


def parse_step_scale(value: str) -> float | str:
    if value == "auto":
        return value
    return float(value)


def main() -> None:
    args = parse_args()
    args.run_id = resolve_run_id(args.run_id)
    args.output = prefixed_path(args.output, args.run_id)
    args.head_step_scale = parse_step_scale(args.head_step_scale)
    text = read_text(args.input)
    vocab = CharVocab.from_text(text)
    samples = make_sample_split(
        text,
        block_size=args.block_size,
        stride=args.stride,
        train_fraction=args.train_fraction,
        max_train_samples=args.max_train_samples,
        max_val_samples=args.max_val_samples,
    )
    train_trie = samples_to_flat_trie(samples.train_samples, vocab)
    val_trie = samples_to_flat_trie(samples.val_samples, vocab)

    writer = RowWriter(args.output)
    try:
        for seed in args.seeds:
            for row in run_baseline(args, vocab, samples, train_trie, val_trie, seed):
                writer.write(row)
                print_row(row)
            for row in run_hybrid(args, vocab, samples, train_trie, val_trie, seed):
                writer.write(row)
                print_row(row)
            print(f"finished seed={seed}", flush=True)
    finally:
        writer.close()
    print(f"wrote {writer.count} rows to {args.output}")


if __name__ == "__main__":
    main()
