from __future__ import annotations

import argparse
import csv
import gc
import resource
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path

import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from agpt_ultra.data import CharVocab, make_circular_samples, make_samples, read_text
from agpt_ultra.eval import evaluate_sequential_text_loss, split_text
from agpt_ultra.flat_ops import collect_batched_flat_head_evidence, flat_trie_negative_log_likelihood, samples_to_flat_trie
from agpt_ultra.head_only import (
    chunk_batched_head_evidence,
    chunked_batched_head_fisher_matvec,
    load_head_theta,
    model_head_theta,
    natural_head_step_matrix_free,
    quadratic_predicted_improvement,
    suggested_quadratic_step_scale,
    trust_radius_step_scale,
)
from agpt_ultra.hybrid import freeze_embeddings, prefix_hidden_state
from agpt_ultra.model import TinyCharRNN
from agpt_ultra.run_ids import prefixed_path, resolve_run_id
from scripts.run_prefix_subtree_train import prefix_ranges


@dataclass(frozen=True)
class PrefixExactHybridRow:
    seed: int
    epoch: int
    prefix_count: int
    sample_count: int
    node_count: int
    predictive_node_count: int
    transition_mass: int
    body_loss: float
    seq_val_nll_before: float
    seq_val_ppl_before: float
    seq_val_bpc_before: float
    seq_val_nll_after_body: float
    seq_val_ppl_after_body: float
    seq_val_bpc_after_body: float
    seq_val_nll_after_head: float
    seq_val_ppl_after_head: float
    seq_val_bpc_after_head: float
    body_lr: float
    body_sec: float
    evidence_sec: float
    solve_sec: float
    eval_sec: float
    cg_iters: int
    step_scale: float
    predicted_improvement: float
    linear_term: float
    fisher_quadratic: float
    eta_quad: float
    eta_trust: float | None
    peak_rss_kb: int


def parse_step_scale(value: str) -> float | str:
    if value == "auto":
        return value
    return float(value)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run exact prefix body-gradient accumulation plus exact merged head update.")
    parser.add_argument("--input", type=Path, default=Path("data/input.txt"))
    parser.add_argument("--output", type=Path, default=Path("runs/prefix_exact_hybrid.csv"))
    parser.add_argument("--run-id", type=str, default=None, help="Prefix output artifacts for a new run. Generated by default.")
    parser.add_argument("--seed", type=int, default=1337)
    parser.add_argument("--block-size", type=int, default=16)
    parser.add_argument("--stride", type=int, default=1)
    parser.add_argument("--prefix-length", type=int, default=1)
    parser.add_argument("--train-fraction", type=float, default=0.9)
    parser.add_argument("--epochs", type=int, default=1)
    parser.add_argument("--hidden-size", type=int, default=64)
    parser.add_argument("--embedding-size", type=int, default=64)
    parser.add_argument("--update-embeddings", action="store_true")
    parser.add_argument("--body-lr", type=float, default=3e-3)
    parser.add_argument("--max-grad-norm", type=float, default=1.0)
    parser.add_argument("--head-damping", type=float, default=50.0)
    parser.add_argument("--head-step-scale", default="auto")
    parser.add_argument("--max-head-step-scale", type=float, default=1.0)
    parser.add_argument("--head-trust-radius", type=float, default=200.0)
    parser.add_argument("--max-cg-iter", type=int, default=8)
    parser.add_argument("--cg-tolerance", type=float, default=1e-6)
    parser.add_argument("--limit-prefixes", type=str, default=None, help="Optional literal prefix list for prefix length 1 smoke runs.")
    parser.add_argument("--max-subtrees", type=int, default=None)
    parser.add_argument("--sequential-val-chunk-size", type=int, default=1024)
    parser.add_argument("--no-circular", action="store_true")
    return parser.parse_args()


def make_model(seed: int, vocab_size: int, embedding_size: int, hidden_size: int, update_embeddings: bool) -> TinyCharRNN:
    torch.manual_seed(seed)
    model = TinyCharRNN(vocab_size, n_embd=embedding_size, n_hidden=hidden_size)
    if not update_embeddings:
        freeze_embeddings(model)
    return model


def evaluate(model: TinyCharRNN, vocab: CharVocab, val_text: str, chunk_size: int) -> tuple[float, float, float, float]:
    started = time.perf_counter()
    metrics = evaluate_sequential_text_loss(model, vocab, val_text, chunk_size=chunk_size)
    return metrics.nll_per_token, metrics.perplexity, metrics.bits_per_char, time.perf_counter() - started


def write_header(path: Path) -> tuple[csv.DictWriter, object]:
    path.parent.mkdir(parents=True, exist_ok=True)
    handle = path.open("w", newline="", encoding="utf-8")
    writer = csv.DictWriter(
        handle,
        fieldnames=list(
            asdict(
                PrefixExactHybridRow(
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    None,
                    0,
                )
            ).keys()
        ),
    )
    writer.writeheader()
    handle.flush()
    return writer, handle


def set_head_requires_grad(model: TinyCharRNN, requires_grad: bool) -> list[bool]:
    previous = [param.requires_grad for param in model.head.parameters()]
    for param in model.head.parameters():
        param.requires_grad_(requires_grad)
    return previous


def restore_head_requires_grad(model: TinyCharRNN, previous: list[bool]) -> None:
    for param, requires_grad in zip(model.head.parameters(), previous, strict=True):
        param.requires_grad_(requires_grad)


def body_parameters(model: TinyCharRNN, update_embeddings: bool) -> list[torch.nn.Parameter]:
    params = [*model.cell.parameters()]
    if update_embeddings:
        params.extend(model.embed.parameters())
    return params


def accumulate_body_gradients(
    model: TinyCharRNN,
    vocab: CharVocab,
    samples: list[str],
    ranges: list[tuple[str, int, int]],
    prefix_length: int,
) -> tuple[float, int, int, int]:
    total_loss = 0.0
    node_count = 0
    predictive_node_count = 0
    transition_mass = 0

    top_samples = [sample[:prefix_length] for sample in samples]
    top_trie = samples_to_flat_trie(top_samples, vocab)
    loss = flat_trie_negative_log_likelihood(model, top_trie)
    total_loss += loss.item()
    loss.backward()
    node_count += top_trie.node_count
    predictive_node_count += int(top_trie.predictive_node_mask.sum().item())
    transition_mass += int(top_trie.transition_counts.sum().item())
    del top_samples, top_trie, loss
    gc.collect()

    for prefix, start, end in ranges:
        prefix_samples = samples[start:end]
        suffixes = [sample[prefix_length:] for sample in prefix_samples]
        trie = samples_to_flat_trie(suffixes, vocab)
        loss = flat_trie_negative_log_likelihood(
            model,
            trie,
            initial_hidden=prefix_hidden_state(model, vocab, prefix),
        )
        total_loss += loss.item()
        loss.backward()
        node_count += trie.node_count
        predictive_node_count += int(trie.predictive_node_mask.sum().item())
        transition_mass += int(trie.transition_counts.sum().item())
        del prefix_samples, suffixes, trie, loss
        gc.collect()

    return total_loss, node_count, predictive_node_count, transition_mass


def collect_exact_head_evidence(
    model: TinyCharRNN,
    vocab: CharVocab,
    samples: list[str],
    ranges: list[tuple[str, int, int]],
    prefix_length: int,
):
    theta = model_head_theta(model)
    evidence = []
    node_count = 0
    predictive_node_count = 0
    transition_mass = 0

    top_samples = [sample[:prefix_length] for sample in samples]
    top_trie = samples_to_flat_trie(top_samples, vocab)
    top_evidence = collect_batched_flat_head_evidence(model, top_trie, theta)
    evidence.append(top_evidence)
    node_count += top_trie.node_count
    predictive_node_count += int(top_trie.predictive_node_mask.sum().item())
    transition_mass += int(top_trie.transition_counts.sum().item())
    del top_trie, top_samples, top_evidence
    gc.collect()

    for prefix, start, end in ranges:
        prefix_samples = samples[start:end]
        suffixes = [sample[prefix_length:] for sample in prefix_samples]
        trie = samples_to_flat_trie(suffixes, vocab)
        chunk = collect_batched_flat_head_evidence(
            model,
            trie,
            theta,
            initial_hidden=prefix_hidden_state(model, vocab, prefix),
        )
        evidence.append(chunk)
        node_count += trie.node_count
        predictive_node_count += int(trie.predictive_node_mask.sum().item())
        transition_mass += int(trie.transition_counts.sum().item())
        del trie, prefix_samples, suffixes, chunk
        gc.collect()

    return theta, chunk_batched_head_evidence(evidence), node_count, predictive_node_count, transition_mass


def main() -> None:
    args = parse_args()
    args.run_id = resolve_run_id(args.run_id)
    args.output = prefixed_path(args.output, args.run_id)
    if args.prefix_length < 1:
        raise ValueError("prefix_length must be at least 1")
    if args.prefix_length >= args.block_size:
        raise ValueError("prefix_length must be smaller than block_size")
    args.head_step_scale = parse_step_scale(args.head_step_scale)

    text = read_text(args.input)
    text_split = split_text(text, train_fraction=args.train_fraction)
    vocab = CharVocab.from_text(text)
    make = make_samples if args.no_circular else make_circular_samples
    started = time.perf_counter()
    samples = make(text_split.train_text, block_size=args.block_size, stride=args.stride)
    sample_sec = time.perf_counter() - started
    started = time.perf_counter()
    samples.sort()
    sort_sec = time.perf_counter() - started
    ranges = prefix_ranges(samples, args.prefix_length)
    if args.limit_prefixes is not None:
        if args.prefix_length != 1:
            raise ValueError("limit_prefixes currently supports prefix_length=1 only")
        allowed = set(args.limit_prefixes)
        ranges = [item for item in ranges if item[0] in allowed]
    if args.max_subtrees is not None:
        ranges = ranges[: args.max_subtrees]

    model = make_model(args.seed, vocab.size, args.embedding_size, args.hidden_size, args.update_embeddings)
    optimizer = torch.optim.AdamW(body_parameters(model, args.update_embeddings), lr=args.body_lr)
    writer, handle = write_header(args.output)
    print(
        f"train_chars={len(text_split.train_text)} val_chars={len(text_split.val_text)} "
        f"samples={len(samples)} prefixes={len(ranges)} block_size={args.block_size} "
        f"prefix_length={args.prefix_length} circular={not args.no_circular} "
        f"run_id={args.run_id} output={args.output} sample_sec={sample_sec:.4f} sort_sec={sort_sec:.4f}",
        flush=True,
    )

    try:
        for epoch in range(1, args.epochs + 1):
            before_nll, before_ppl, before_bpc, before_eval_sec = evaluate(
                model,
                vocab,
                text_split.val_text,
                args.sequential_val_chunk_size,
            )

            body_started = time.perf_counter()
            optimizer.zero_grad(set_to_none=True)
            head_requires_grad = set_head_requires_grad(model, False)
            try:
                body_loss, body_nodes, body_predictive, body_mass = accumulate_body_gradients(
                    model,
                    vocab,
                    samples,
                    ranges,
                    args.prefix_length,
                )
                if args.max_grad_norm is not None:
                    torch.nn.utils.clip_grad_norm_(body_parameters(model, args.update_embeddings), args.max_grad_norm)
                optimizer.step()
            finally:
                restore_head_requires_grad(model, head_requires_grad)
            body_sec = time.perf_counter() - body_started
            after_body_nll, after_body_ppl, after_body_bpc, after_body_eval_sec = evaluate(
                model,
                vocab,
                text_split.val_text,
                args.sequential_val_chunk_size,
            )

            evidence_started = time.perf_counter()
            theta, merged, head_nodes, head_predictive, head_mass = collect_exact_head_evidence(
                model,
                vocab,
                samples,
                ranges,
                args.prefix_length,
            )
            evidence_sec = time.perf_counter() - evidence_started

            solve_started = time.perf_counter()
            cg = natural_head_step_matrix_free(
                merged,
                damping=args.head_damping,
                max_cg_iter=args.max_cg_iter,
                cg_tolerance=args.cg_tolerance,
            )
            fisher_delta = chunked_batched_head_fisher_matvec(cg.solution, merged)
            linear_term = merged.gradient.dot(cg.solution).item()
            fisher_quadratic = cg.solution.dot(fisher_delta).item()
            eta_quad = suggested_quadratic_step_scale(
                merged.gradient,
                cg.solution,
                fisher_delta,
                max_step_scale=args.max_head_step_scale,
            )
            eta_trust = trust_radius_step_scale(fisher_quadratic, args.head_trust_radius)
            if args.head_step_scale == "auto":
                step_scale = eta_quad
                if eta_trust is not None:
                    step_scale = min(step_scale, eta_trust)
            else:
                step_scale = float(args.head_step_scale)
            predicted_improvement = quadratic_predicted_improvement(
                merged.gradient,
                cg.solution,
                fisher_delta,
                step_scale,
            )
            load_head_theta(model, theta + step_scale * cg.solution)
            solve_sec = time.perf_counter() - solve_started
            del merged, fisher_delta
            gc.collect()

            after_head_nll, after_head_ppl, after_head_bpc, after_head_eval_sec = evaluate(
                model,
                vocab,
                text_split.val_text,
                args.sequential_val_chunk_size,
            )
            row = PrefixExactHybridRow(
                args.seed,
                epoch,
                len(ranges),
                len(samples),
                head_nodes,
                head_predictive,
                head_mass,
                body_loss,
                before_nll,
                before_ppl,
                before_bpc,
                after_body_nll,
                after_body_ppl,
                after_body_bpc,
                after_head_nll,
                after_head_ppl,
                after_head_bpc,
                args.body_lr,
                body_sec,
                evidence_sec,
                solve_sec,
                before_eval_sec + after_body_eval_sec + after_head_eval_sec,
                cg.iterations,
                step_scale,
                predicted_improvement,
                linear_term,
                fisher_quadratic,
                eta_quad,
                eta_trust,
                resource.getrusage(resource.RUSAGE_SELF).ru_maxrss,
            )
            writer.writerow(asdict(row))
            handle.flush()
            print(
                f"epoch={epoch:03d} prefixes={len(ranges)} nodes={head_nodes} mass={head_mass} "
                f"seq_val_ppl={before_ppl:.2f}->{after_body_ppl:.2f}->{after_head_ppl:.2f} "
                f"body_loss={body_loss:.4f} body_sec={body_sec:.2f} "
                f"evidence_sec={evidence_sec:.2f} solve_sec={solve_sec:.2f} "
                f"cg={cg.iterations} step_scale={step_scale} peak_rss_mb={row.peak_rss_kb / 1024:.1f}",
                flush=True,
            )
            if (body_nodes, body_predictive, body_mass) != (head_nodes, head_predictive, head_mass):
                print(
                    f"warning=body_head_stats_differ body_nodes={body_nodes} head_nodes={head_nodes} "
                    f"body_mass={body_mass} head_mass={head_mass}",
                    flush=True,
                )
    finally:
        handle.close()
    print(f"wrote={args.output}", flush=True)


if __name__ == "__main__":
    main()
