from __future__ import annotations

import argparse
import csv
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path

import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from agpt_ultra.data import CharVocab, read_text
from agpt_ultra.eval import evaluate_trie_loss, make_sample_split
from agpt_ultra.hybrid import freeze_embeddings, hybrid_epoch
from agpt_ultra.model import TinyCharRNN
from agpt_ultra.run_ids import prefixed_path, resolve_run_id
from agpt_ultra.stats import trie_stats


@dataclass(frozen=True)
class SweepRow:
    block_size: int
    epoch: int
    train_samples: int
    val_samples: int
    nodes: int
    predictive_nodes: int
    singleton_fraction: float
    branching_fraction: float
    mean_count: float
    mean_entropy: float
    weighted_mean_entropy: float
    train_loss: float
    val_nll: float
    val_ppl: float
    runtime_sec: float
    cg_iters: int | None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Sweep block size for trie Fisher hybrid training.")
    parser.add_argument("--input", type=Path, default=Path("data/input.txt"))
    parser.add_argument("--output", type=Path, default=Path("runs/block_sweep.csv"))
    parser.add_argument("--run-id", type=str, default=None, help="Prefix output artifacts for a new run. Generated by default.")
    parser.add_argument("--block-sizes", type=int, nargs="+", default=[8, 12, 16, 24, 32])
    parser.add_argument("--stride", type=int, default=None)
    parser.add_argument("--max-train-samples", type=int, default=512)
    parser.add_argument("--max-val-samples", type=int, default=128)
    parser.add_argument("--epochs", type=int, default=2)
    parser.add_argument("--seed", type=int, default=1337)
    parser.add_argument("--hidden-size", type=int, default=8)
    parser.add_argument("--embedding-size", type=int, default=8)
    parser.add_argument("--body-lr", type=float, default=3e-3)
    parser.add_argument("--head-damping", type=float, default=50.0)
    parser.add_argument("--head-step-scale", type=float, default=0.5)
    parser.add_argument("--max-cg-iter", type=int, default=32)
    parser.add_argument("--cg-tolerance", type=float, default=1e-6)
    parser.add_argument("--max-grad-norm", type=float, default=1.0)
    return parser.parse_args()


def write_row(path: Path, row: SweepRow, write_header: bool) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    mode = "w" if write_header else "a"
    with path.open(mode, newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(asdict(row).keys()))
        if write_header:
            writer.writeheader()
        writer.writerow(asdict(row))


def main() -> None:
    args = parse_args()
    args.run_id = resolve_run_id(args.run_id)
    args.output = prefixed_path(args.output, args.run_id)
    text = read_text(args.input)
    vocab = CharVocab.from_text(text)
    wrote_header = False

    for block_size in args.block_sizes:
        stride = args.stride if args.stride is not None else block_size
        split = make_sample_split(
            text,
            block_size=block_size,
            stride=stride,
            max_train_samples=args.max_train_samples,
            max_val_samples=args.max_val_samples,
        )
        stats = trie_stats(split.train_samples, vocab)
        torch.manual_seed(args.seed)
        model = TinyCharRNN(vocab.size, n_embd=args.embedding_size, n_hidden=args.hidden_size)
        freeze_embeddings(model)
        optimizer = torch.optim.AdamW(model.cell.parameters(), lr=args.body_lr)

        val = evaluate_trie_loss(model, vocab, split.val_samples)
        row = SweepRow(
            block_size=block_size,
            epoch=0,
            train_samples=len(split.train_samples),
            val_samples=len(split.val_samples),
            nodes=stats.nodes,
            predictive_nodes=stats.predictive_nodes,
            singleton_fraction=stats.singleton_fraction,
            branching_fraction=stats.branching_fraction,
            mean_count=stats.mean_count,
            mean_entropy=stats.mean_entropy,
            weighted_mean_entropy=stats.weighted_mean_entropy,
            train_loss=float("nan"),
            val_nll=val.nll_per_token,
            val_ppl=val.perplexity,
            runtime_sec=0.0,
            cg_iters=None,
        )
        write_row(args.output, row, write_header=not wrote_header)
        wrote_header = True
        print(asdict(row), flush=True)

        for epoch in range(1, args.epochs + 1):
            started = time.perf_counter()
            result = hybrid_epoch(
                model,
                vocab,
                split.train_samples,
                body_optimizer=optimizer,
                head_damping=args.head_damping,
                head_step_scale=args.head_step_scale,
                max_grad_norm=args.max_grad_norm,
                max_cg_iter=args.max_cg_iter,
                cg_tolerance=args.cg_tolerance,
            )
            runtime = time.perf_counter() - started
            val = evaluate_trie_loss(model, vocab, split.val_samples)
            row = SweepRow(
                block_size=block_size,
                epoch=epoch,
                train_samples=len(split.train_samples),
                val_samples=len(split.val_samples),
                nodes=stats.nodes,
                predictive_nodes=stats.predictive_nodes,
                singleton_fraction=stats.singleton_fraction,
                branching_fraction=stats.branching_fraction,
                mean_count=stats.mean_count,
                mean_entropy=stats.mean_entropy,
                weighted_mean_entropy=stats.weighted_mean_entropy,
                train_loss=result.after_loss,
                val_nll=val.nll_per_token,
                val_ppl=val.perplexity,
                runtime_sec=runtime,
                cg_iters=result.head_result.cg_iterations,
            )
            write_row(args.output, row, write_header=False)
            print(asdict(row), flush=True)


if __name__ == "__main__":
    main()
